// src/App.tsx
/*!
Copyright 2016-2020 Brazil Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import React from "react";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { createStore, applyMiddleware } from "redux";
import createSagaMiddleware from "redux-saga";
import { persistReducer, persistStore, PersistConfig } from "redux-persist";

import AppNavigator from "./navigators";
import Splash from "./components/Splash";
import rootReducer, { rootSaga, RootState } from "./modules";
import init from "./utils/init";
import persistConfig from "./config/persist";

const App = () => {
  return (
    <Provider store={store}>
      <PersistGate
        loading={<Splash />}
        onBeforeLift={onBeforeLift}
        persistor={persistor as any}
      >
        <AppNavigator />
      </PersistGate>
    </Provider>
  );
};
export default App;

const sagaMiddleware = createSagaMiddleware();
const persistedReducer = persistReducer(
  persistConfig as PersistConfig<RootState>,
  rootReducer
);
const store = createStore(persistedReducer, applyMiddleware(sagaMiddleware));
const persistor = persistStore(store);
sagaMiddleware.run(rootSaga);

const onBeforeLift = () => {
  init(store);
};

// miyoutv/src/app/app.component.ts
/*!
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { Component } from '@angular/core';

@Component({
  selector: 'miyoutv',
  templateUrl: 'app.component.html',
})
export class AppComponent { }

<!DOCTYPE html>
<!--
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<meta charset="UTF-8">
<form style="width:0; height:0; overflow: hidden;">
    <input type="text" tabindex="-1">
    <input type="password" tabindex="-1">
</form>
<div class="app"></div>
