// src/containers/Titlebar.tsx
/*!
Copyright 2016-2019 Brazil Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import React, { Component } from "react";
import { TouchableOpacity, View, StyleSheet, Platform } from "react-native";
import { Image, Text } from "react-native-elements";
import FontAwesome5Icon from "react-native-vector-icons/FontAwesome5";
import { connect } from "react-redux";
import { Dispatch } from "redux";

import colorStyle, { active, black, dark, light } from "../styles/color";
import containerStyle from "../styles/container";
import { WindowActions, WindowState } from "../modules/window";
import { appName } from "../config/constants";

type Props = {
  dispatch: Dispatch;
  window: WindowState;
};
type State = {
  containerWidth: number;
};
class Titlebar extends Component<Props, State> {
  state = {
    containerWidth: 0
  };
  layoutCallbackId?: number;

  render() {
    const { window } = this.props;
    const { containerWidth } = this.state;
    const { alwaysOnTop, fullScreen, maximized, title } = window;
    if (Platform.OS !== "web" || fullScreen) {
      return null;
    }
    return (
      <div className="titlebar">
        <style>{cssStyles}</style>
        <View
          style={[containerStyle.row, colorStyle.bgBlack]}
          onLayout={({ nativeEvent }) => {
            if (this.layoutCallbackId != null) {
              clearTimeout(this.layoutCallbackId);
            }
            const { layout } = nativeEvent;
            const containerWidth = layout.width;
            this.layoutCallbackId = setTimeout(() => {
              this.setState({ containerWidth });
            }, 200);
          }}
        >
          <View
            style={[styles.contents, containerStyle.row, containerStyle.left]}
          >
            <Image
              containerStyle={styles.iconContainer}
              placeholderStyle={colorStyle.bgTransparent}
              style={styles.icon}
              source={require("../../assets/icon_16x16.png")}
            />
          </View>
          {containerWidth > breakpoint && (
            <View
              style={[
                styles.contents,
                containerStyle.row,
                containerStyle.center
              ]}
            >
              <Text style={[colorStyle.light, styles.title]}>
                {title || appName}
              </Text>
            </View>
          )}
          <View
            style={[styles.contents, containerStyle.row, containerStyle.right]}
          >
            <div className="button">
              <TouchableOpacity
                style={styles.button}
                onPress={() => {
                  const { dispatch, window } = this.props;
                  const { alwaysOnTop } = window;
                  dispatch(WindowActions.setAlwaysOnTop(!alwaysOnTop));
                }}
              >
                <FontAwesome5Icon
                  name="thumbtack"
                  solid
                  color={alwaysOnTop ? active : light}
                />
              </TouchableOpacity>
            </div>
            <div className="button">
              <TouchableOpacity
                style={styles.button}
                onPress={() => {
                  const { dispatch } = this.props;
                  dispatch(WindowActions.minimize());
                }}
              >
                <FontAwesome5Icon name="window-minimize" solid color={light} />
              </TouchableOpacity>
            </div>

            {maximized ? (
              <div className="button">
                <TouchableOpacity
                  style={styles.button}
                  onPress={() => {
                    const { dispatch } = this.props;
                    dispatch(WindowActions.restore());
                  }}
                >
                  <FontAwesome5Icon name="window-restore" solid color={light} />
                </TouchableOpacity>
              </div>
            ) : (
              <div className="button">
                <TouchableOpacity
                  style={styles.button}
                  onPress={() => {
                    const { dispatch } = this.props;
                    dispatch(WindowActions.maximize());
                  }}
                >
                  <FontAwesome5Icon
                    name="window-maximize"
                    solid
                    color={light}
                  />
                </TouchableOpacity>
              </div>
            )}
            <div className="button">
              <TouchableOpacity
                style={styles.button}
                onPress={() => {
                  const { dispatch, window } = this.props;
                  const { fullScreen } = window;
                  dispatch(WindowActions.setFullScreen(!fullScreen));
                }}
              >
                <FontAwesome5Icon name="square-full" solid color={light} />
              </TouchableOpacity>
            </div>
            <div className="button close">
              <TouchableOpacity
                style={styles.button}
                onPress={() => {
                  const { dispatch } = this.props;
                  dispatch(WindowActions.close());
                }}
              >
                <FontAwesome5Icon name="times" solid color={light} />
              </TouchableOpacity>
            </div>
          </View>
        </View>
      </div>
    );
  }

  componentWillUnmount() {
    clearTimeout(this.layoutCallbackId);
  }
}

export default connect(({ window }: { window: WindowState }) => ({ window }))(
  Titlebar
);

const breakpoint = 768;
const styles = StyleSheet.create({
  contents: {
    flex: 1
  },
  iconContainer: {
    alignItems: "center",
    height: 24,
    justifyContent: "center",
    width: 24
  },
  icon: {
    height: 16,
    width: 16
  },
  title: {
    height: 19,
    overflow: "hidden"
  },
  button: {
    alignItems: "center",
    flexDirection: "row",
    height: 24,
    justifyContent: "center",
    width: 32
  }
});

const cssStyles = `
  #react-app{
    border: 2px solid ${dark};
  }

  .titlebar {
    border-bottom: 2px solid ${black};
    user-select: none;
    -webkit-app-region: drag;
  }

  .titlebar .button {
    -webkit-app-region: no-drag;
  }
  .titlebar .button:hover {
    background-color: #070707;
  }
  .titlebar .close:hover {
    background-color: #d32535;
  }
`;

// miyoutv/src/app/core/titlebar.component.ts
/*!
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import { ChangeDetectorRef, Component } from '@angular/core';

import { WindowService } from '../shared/window.service';

@Component({
  selector: 'titlebar',
  templateUrl: './titlebar.component.html',
})
export class TitlebarComponent {
  constructor(
    private changeDetectorRef: ChangeDetectorRef,
    private windowService: WindowService,
  ) { }

  get isFullscreen(): boolean {
    return this.windowService.fullscreen;
  }
  get isMaximized(): boolean {
    return this.windowService.isMaximized;
  }
  get isAlwaysOnTop(): boolean {
    return this.windowService.alwaysOnTop;
  }

  public toggleAlwaysOnTop() {
    this.windowService.alwaysOnTop = !this.windowService.alwaysOnTop;
    this.changeDetectorRef.detectChanges();
  }

  public minimize() {
    this.windowService.minimize();
    this.changeDetectorRef.detectChanges();
  }

  public maximize() {
    this.windowService.maximize();
    this.changeDetectorRef.detectChanges();
  }

  public restore() {
    this.windowService.restore();
    this.changeDetectorRef.detectChanges();
  }

  public fullscreen() {
    this.windowService.fullscreen = true;
    this.changeDetectorRef.detectChanges();
  }

  public close() {
    this.windowService.close();
  }
}

<!DOCTYPE html>
<!--
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<meta charset="UTF-8">
<div class="titlebar row mx-0 bg-dark">
    <div class="d-none d-md-block col-md-4 text-left"><img src="miyoutv.ico" width="20" height="20"></div>
    <div class="d-none d-md-block col-md-4 text-center">MiyouTV</div>
    <div class="col-12 col-md-4 px-0 text-right">
        <button class="btn btn-sm btn-win" title="常に前面に表示" (click)="toggleAlwaysOnTop()">
            <span class="fa fa-fw fa-thumb-tack" [class.text-primary]="isAlwaysOnTop"></span>
        </button>
        <button class="btn btn-sm btn-win" title="最小化" (click)="minimize()">
            <span class="fa fa-fw fa-window-minimize"></span>
        </button>
        <button class="btn btn-sm btn-win" title="最大化" [class.d-none]="isMaximized" (click)="maximize()">
            <span class="fa fa-fw fa-window-maximize"></span>
        </button>
        <button class="btn btn-sm btn-win" title="元のサイズに戻す" [class.d-none]="!isMaximized" (click)="restore()">
            <span class="fa fa-fw fa-window-restore"></span>
        </button>
        <button class="btn btn-sm btn-win" title="全画面表示" (click)="fullscreen()">
            <span class="fa fa-fw fa-square"></span>
        </button>
        <button class="btn btn-sm btn-win btn-win-close" title="閉じる" (click)="close()">
            <span class="fa fa-fw fa-times"></span>
        </button>
    </div>
</div>
