// src/containers/Seekbar.tsx
/*!
Copyright 2016-2019 Brazil Ltd.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

import React, { Component } from "react";
import { TouchableOpacity, View, StyleSheet } from "react-native";
import { Text } from "react-native-elements";
import FontAwesome5Icon from "react-native-vector-icons/FontAwesome5";
import { connect } from "react-redux";
import { Dispatch } from "redux";

import CommentChart from "./CommentChart";
import CustomSlider from "../components/CustomSlider";
import colorStyle, { gray, light } from "../styles/color";
import containerStyle from "../styles/container";
import { PlayerState, PlayerActions } from "../modules/player";
import { SettingState } from "../modules/setting";
import { ViewerState, ViewerActions } from "../modules/viewer";
import DateFormatter from "../utils/DateFormatter";
import formatTime from "../utils/formatTime";

type Props = {
  dispatch: Dispatch;
  player: PlayerState;
  setting: SettingState & {
    view?: {
      hourFirst?: string;
      hourFormat?: string;
    };
  };
  viewer: ViewerState;
};
class Seekbar extends Component<Props> {
  options: { [key: string]: string } = {
    "ad-lavc-o": "dual_mono_mode=auto"
  };
  observers: { [name: string]: (value: any) => void } = {};

  render() {
    const { player, setting, viewer } = this.props;
    const { duration, time, position, useClock } = player;
    const { view = {} } = setting;
    const { hourFirst = "4", hourFormat = "" } = view;
    const { programs, index, extraIndex } = viewer;

    const program = programs[index];
    const recordedProgram = this.getRecorded();
    const date = new Date(recordedProgram.start);

    const dateFormatter = new DateFormatter(
      parseInt(hourFirst, 10),
      hourFormat
    );

    return (
      <View style={[containerStyle.row, styles.container]}>
        {program.recorded && (
          <TouchableOpacity
            style={styles.button}
            disabled={!program.recorded[extraIndex - 1]}
            onPress={() => {
              this.prev();
            }}
          >
            <FontAwesome5Icon
              name="step-backward"
              solid
              color={program.recorded[extraIndex - 1] ? light : gray}
              size={24}
            />
          </TouchableOpacity>
        )}
        <TouchableOpacity
          onPress={() => {
            const { dispatch, player } = this.props;
            const { useClock } = player;
            dispatch(PlayerActions.useClock(!useClock));
          }}
        >
          <Text style={colorStyle.light}>
            {useClock
              ? dateFormatter.format(
                  new Date(date.getTime() + time),
                  "HHHH:mm:ss"
                )
              : formatTime(time)}
          </Text>
        </TouchableOpacity>
        <View style={styles.sliderContainer}>
          <CommentChart />
          <CustomSlider
            style={styles.slider}
            maximumValue={1}
            minimumValue={0}
            step={0.00001}
            value={position}
            maximumTrackTintColor="#ffffff20"
            minimumTrackTintColor="#ffffffe2"
            onValueChange={position => {
              const { dispatch } = this.props;
              dispatch(PlayerActions.position(position));
            }}
          />
        </View>
        <TouchableOpacity
          onPress={() => {
            const { dispatch, player } = this.props;
            const { useClock } = player;
            dispatch(PlayerActions.useClock(!useClock));
          }}
        >
          <Text style={colorStyle.light}>
            {useClock
              ? dateFormatter.format(
                  new Date(date.getTime() + duration),
                  "HHHH:mm:ss"
                )
              : formatTime(duration)}
          </Text>
        </TouchableOpacity>
        {program.recorded && (
          <TouchableOpacity
            style={styles.button}
            disabled={!program.recorded[extraIndex + 1]}
            onPress={() => {
              this.next();
            }}
          >
            <FontAwesome5Icon
              name="step-forward"
              solid
              color={program.recorded[extraIndex + 1] ? light : gray}
              size={24}
            />
          </TouchableOpacity>
        )}
      </View>
    );
  }

  shouldComponentUpdate(nextProps: Props) {
    const { player } = this.props;
    return (
      nextProps.player === player ||
      (nextProps.player.time === player.time &&
        nextProps.player.position === player.position) ||
      Math.floor(nextProps.player.time / 1000) !==
        Math.floor(player.time / 1000)
    );
  }

  getRecorded() {
    const { viewer } = this.props;
    const { programs, index, extraIndex } = viewer;
    const program = programs[index];
    if (program.recorded && program.recorded[extraIndex]) {
      return program.recorded[extraIndex];
    }
    return program;
  }

  next() {
    const { dispatch, viewer } = this.props;
    const { programs, index, extraIndex } = viewer;
    const program = programs[index];
    const nextExtraIndex = extraIndex + 1;
    if (program.recorded && program.recorded[nextExtraIndex]) {
      dispatch(
        ViewerActions.update({ extraIndex: nextExtraIndex, peakPlay: false })
      );
    }
  }

  prev() {
    const { dispatch, viewer } = this.props;
    const { programs, index, extraIndex } = viewer;
    const program = programs[index];
    const prevExtraIndex = extraIndex - 1;
    if (program.recorded && program.recorded[prevExtraIndex]) {
      dispatch(
        ViewerActions.update({ extraIndex: prevExtraIndex, peakPlay: false })
      );
    }
  }
}

export default connect(
  ({
    player,
    setting,
    viewer
  }: {
    player: PlayerState;
    setting: SettingState;
    viewer: ViewerState;
  }) => ({
    player,
    setting,
    viewer
  })
)(Seekbar);

const styles = StyleSheet.create({
  container: {
    minHeight: 40
  },
  sliderContainer: {
    flex: 1,
    height: 40
  },
  slider: {
    bottom: 0,
    position: "absolute",
    left: 0,
    right: 0,
    top: 0
  },
  button: {
    alignItems: "center",
    flexDirection: "row",
    height: 40,
    justifyContent: "center",
    width: 40
  }
});

// miyoutv/src/app/player/seekbar.component.ts
/*!
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
import {
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
} from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Subscription } from 'rxjs';

import { StorageService } from '../shared/storage.service';
import { Player } from './player.service';

@Component({
  selector: 'seekbar',
  templateUrl: 'seekbar.component.html',
})
export class SeekbarComponent implements OnInit, OnDestroy {
  @Input() public offset: Date;
  @Input() public showPrevious: boolean;
  @Input() public showNext: boolean;
  @Input() public chapters: number[] = [];
  @Input() public chartPoints: string;
  @Output() public previous: EventEmitter<null> = new EventEmitter();
  @Output() public next: EventEmitter<null> = new EventEmitter();
  public form: FormGroup;
  public hourFirst: number = 4;
  public hourFormat: string = '';
  public useClock: boolean = true;
  public time: number = 0;
  public length: number = 0;
  public clockTime: Date;
  public endTime: Date;
  public isSeeking: boolean = false;
  private subscriptions: Subscription[] = [];

  constructor(
    private changeDetectorRef: ChangeDetectorRef,
    private formBuilder: FormBuilder,
    private storageService: StorageService,
    private player: Player,
  ) { }

  public ngOnInit() {
    this.hourFirst = this.storageService.loadLocalStorage('hourFirst');
    this.hourFormat = this.storageService.loadLocalStorage('hourFormat') || '';
    if (this.hourFirst == null) {
      this.hourFirst = 4;
    }
    this.form = this.formBuilder.group({
      position: [0],
    });
    this.subscriptions.push(
      this.form.valueChanges.subscribe((data) => {
        if (this.isSeeking) {
          this.player.position = data.position;
        }
      }),
      this.player.event.filter((event: any): boolean => (
        event.name === 'PositionChanged'
      )).subscribe((event: any) => {
        if (!this.isSeeking) {
          this.form.patchValue({ position: event.position }, { emitEvent: false });
        }
        this.time = this.player.time;
        this.length = this.player.length;
        if (this.offset) {
          this.clockTime = new Date(this.offset.getTime() + this.time);
          this.endTime = new Date(this.offset.getTime() + this.length);
        }
        this.changeDetectorRef.detectChanges();
      }),
    );
  }

  public ngOnDestroy() {
    this.subscriptions.forEach((a: Subscription) => {
      a.unsubscribe();
    });
  }
}

<!DOCTYPE html>
<!--
Copyright 2016-2018 Brazil Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<meta charset="UTF-8">
<form class="seekbar w-100" [formGroup]="form">
    <div class="form-group w-100 m-0 p-1">
        <div class="input-group input-group-media w-100 flex">
            <div class="input-group-prepend">
                <button class="btn btn-media" type="button" *ngIf="showPrevious" (click)="previous.emit()">
                    <img class="img-icon-md" src="assets/step-backward.svg" alt="">
                </button>
            </div>
            <div class="input-group-prepend">
                <span class="input-group-text border-0 bg-transparent text-light clickable" (click)="useClock = !useClock">{{useClock && clockTime ? (clockTime | dateEx:hourFirst:hourFormat:'HHHH:mm:ss') : (time | formatTime)}}</span>
            </div>
            <div class="position-relative flex-fill">
                <svg class="sliderchart fit" width="100%" height="100%" viewBox="0 0 100 100" preserveAspectRatio="none">
                    <polyline class="chart-line" vector-effect="non-scaling-stroke" [attr.points]="chartPoints"></polyline>
                    <line class="chart-separator" vector-effect="non-scaling-stroke" y1="0" y2="100" *ngFor="let chapter of chapters" [attr.x1]="chapter * 100"[attr.x2]="chapter * 100"></line>
                </svg>
                <input class="form-control form-control-range fit bg-transparent" type="range" step="0.00001" min="0" max="1" list="chapters" formControlName="position" (mousedown)="isSeeking = true" (mouseup)="isSeeking = false; true">
                <datalist id="chapters">
                    <option *ngFor="let chapter of chapters" [value]="chapter"></option>
                </datalist>
            </div>
            <div class="input-group-append">
                <span class="input-group-text border-0 bg-transparent text-light clickable" (click)="useClock = !useClock">{{useClock && endTime ? (endTime | dateEx:hourFirst:hourFormat:'HHHH:mm:ss') : (length | formatTime)}}</span>
            </div>
            <div class="input-group-append">
                <button class="btn btn-media" type="button" *ngIf="showNext" (click)="next.emit()">
                    <img class="img-icon-md" src="assets/step-forward.svg" alt="">
                </button>
            </div>
        </div>
    </div>
</form>
